import {CONFIG,money,dateISO,prettyDate,escapeHTML,parseDate} from "./config.js";
import {Storage} from "./storage.js";
import {Services} from "./services.js";
import {renderCalendar,isDayBlocked,availableSlots,slotAvailable} from "./calendar.js";
const $=s=>document.querySelector(s);let adminMonth=new Date();adminMonth.setDate(1);let selectedAdminDate=null;
const logged=()=>sessionStorage.getItem("lecortes_admin_demo")==="1";
function showDashboard(){ $("#login-screen").hidden=true;$("#dashboard").hidden=false;$("#logout").hidden=false;renderAll() }
$("#login-form").addEventListener("submit",e=>{e.preventDefault();if($("#admin-password").value===CONFIG.adminPassword){sessionStorage.setItem("lecortes_admin_demo","1");$("#login-error").textContent="";showDashboard()}else $("#login-error").textContent="Senha incorreta. Confira a senha demonstrativa."});
$("#logout").addEventListener("click",()=>{sessionStorage.removeItem("lecortes_admin_demo");location.reload()});
if(logged())showDashboard();
function renderStats(){const a=Storage.getAppointments(),today=dateISO(new Date()),active=a.filter(x=>x.status!=="Cancelado");$("#stat-total").textContent=a.length;$("#stat-today").textContent=active.filter(x=>x.date===today).length;$("#stat-upcoming").textContent=active.filter(x=>x.date>=today&&["Pendente","Confirmado"].includes(x.status)).length;$("#stat-cancelled").textContent=a.filter(x=>x.status==="Cancelado").length}
function renderAppointments(){const filter=$("#status-filter").value,arr=Storage.getAppointments().filter(a=>filter==="all"||a.status===filter).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$("#appointment-rows").innerHTML=arr.map(a=>`<tr><td>${escapeHTML(a.name)}<br><small>${escapeHTML(a.phone)}</small></td><td>${escapeHTML(a.serviceName)}</td><td>${escapeHTML(a.date.split("-").reverse().join("/"))}</td><td>${escapeHTML(a.time)}</td><td>${money(a.price)}</td><td><span class="status status-${a.status.toLowerCase()}">${a.status}</span></td><td><div class="row-actions"><button class="small-action" data-act="view" data-id="${a.id}">Ver</button>${a.status!=="Cancelado"?`<button class="small-action" data-act="confirm" data-id="${a.id}">Confirmar</button><button class="small-action" data-act="cancel" data-id="${a.id}">Cancelar</button>`:""}<button class="small-action" data-act="delete" data-id="${a.id}">Excluir</button></div></td></tr>`).join("");$("#appointment-empty").hidden=arr.length>0;$("#appointment-rows").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>appointmentAction(b.dataset.act,b.dataset.id)))}
function appointmentAction(act,id){let a=Storage.getAppointments(),item=a.find(x=>x.id===id);if(!item)return;if(act==="view"){$("#detail-content").innerHTML=`<span>Código</span><strong>${escapeHTML(item.id)}</strong><span>Cliente</span><strong>${escapeHTML(item.name)}</strong><span>Telefone</span><strong>${escapeHTML(item.phone)}</strong><span>Serviço</span><strong>${escapeHTML(item.serviceName)}</strong><span>Data</span><strong>${escapeHTML(prettyDate(item.date))}</strong><span>Horário</span><strong>${escapeHTML(item.time)}</strong><span>Valor</span><strong>${money(item.price)}</strong><span>Status</span><strong>${item.status}</strong>`;$("#detail-modal").hidden=false;return}if(act==="delete"&&!confirm("Excluir permanentemente este registro da demonstração?"))return;if(act==="cancel"&&!confirm("Cancelar este agendamento?"))return;if(act==="delete")a=a.filter(x=>x.id!==id);else if(act==="cancel")item.status="Cancelado";else if(act==="confirm")item.status="Confirmado";Storage.saveAppointments(a);renderAll()}
$("#detail-close").addEventListener("click",()=>$("#detail-modal").hidden=true);$("#detail-modal").addEventListener("click",e=>{if(e.target===$("#detail-modal"))$("#detail-modal").hidden=true});$("#status-filter").addEventListener("change",renderAppointments);
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===btn));["appointments","calendar","services","settings"].forEach(k=>$("#panel-"+k).hidden=k!==btn.dataset.tab);if(btn.dataset.tab==="calendar")renderAdminCalendar()}));
function renderAdminCalendar(){renderCalendar({monthDate:adminMonth,container:$("#admin-days"),label:$("#admin-month"),selected:selectedAdminDate,onSelect:date=>{selectedAdminDate=date;renderAdminCalendar();renderBlocks()},admin:true});$("#admin-prev").disabled=adminMonth.getFullYear()===new Date().getFullYear()&&adminMonth.getMonth()===new Date().getMonth()}
$("#admin-prev").addEventListener("click",()=>{adminMonth.setMonth(adminMonth.getMonth()-1);renderAdminCalendar()});$("#admin-next").addEventListener("click",()=>{adminMonth.setMonth(adminMonth.getMonth()+1);renderAdminCalendar()});
function renderBlocks(){const chosen=selectedAdminDate;$("#block-date").textContent=chosen?prettyDate(chosen):"Selecione um dia";$("#toggle-day-block").disabled=!chosen;$("#block-time").innerHTML='<option value="">Selecione um horário</option>'+CONFIG.timeSlots.map(t=>`<option value="${t}">${t}</option>`).join("");$("#add-time-block").disabled=!chosen;const blocks=Storage.getBlocks().filter(b=>b.date===chosen);const day=blocks.some(b=>b.type==="day");$("#toggle-day-block").textContent=day?"Desbloquear dia inteiro":"Bloquear dia inteiro";$("#toggle-day-block").disabled=!chosen||Storage.getAppointments().some(a=>a.date===chosen&&a.status!=="Cancelado")&&!day;$("#block-list").innerHTML=blocks.length?blocks.map(b=>`<div class="block-row"><span>${b.type==="day"?"Dia inteiro":`Horário ${b.time}`}</span><button data-id="${b.id}">Desbloquear</button></div>`).join(""):'<p class="empty-note">Nenhum bloqueio cadastrado.</p>';$("#block-list").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{Storage.saveBlocks(Storage.getBlocks().filter(x=>x.id!==b.dataset.id));renderBlocks();renderAdminCalendar()}))}
$("#toggle-day-block").addEventListener("click",()=>{if(!selectedAdminDate)return;let blocks=Storage.getBlocks(),existing=blocks.find(b=>b.date===selectedAdminDate&&b.type==="day");if(existing)blocks=blocks.filter(b=>b.id!==existing.id);else{if(blocks.some(b=>b.date===selectedAdminDate&&b.type==="time")){if(!confirm("Já existem bloqueios por horário. Substituí-los por bloqueio do dia inteiro?"))return;blocks=blocks.filter(b=>b.date!==selectedAdminDate)}blocks.push({id:"B-"+Date.now(),date:selectedAdminDate,type:"day"})}Storage.saveBlocks(blocks);renderBlocks();renderAdminCalendar()});
$("#add-time-block").addEventListener("click",()=>{const time=$("#block-time").value;if(!selectedAdminDate||!time)return;if(!slotAvailable(selectedAdminDate,time)){alert("Este horário já está reservado ou bloqueado.");return}const b=Storage.getBlocks();b.push({id:"B-"+Date.now(),date:selectedAdminDate,type:"time",time});Storage.saveBlocks(b);renderBlocks();renderAdminCalendar()});
function renderServices(){const all=Services.all();$("#admin-service-list").innerHTML=all.map(s=>`<div class="admin-service-row"><strong>${escapeHTML(s.name)}</strong><span>${money(s.price)}</span><div><button class="small-action" data-edit="${s.id}">Editar</button><button class="small-action" data-remove="${s.id}">Remover</button></div></div>`).join("");$("#admin-service-list").querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>{const s=Services.get(b.dataset.edit);$("#service-id").value=s.id;$("#service-name").value=s.name;$("#service-price").value=s.price;$("#cancel-service-edit").hidden=false}));$("#admin-service-list").querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{if(confirm("Remover este serviço da lista pública? Registros antigos serão mantidos.")){Services.remove(b.dataset.remove);renderServices()}}))}
$("#service-form").addEventListener("submit",e=>{e.preventDefault();const id=$("#service-id").value||"svc-"+Date.now(),name=$("#service-name").value.trim(),price=Number($("#service-price").value);if(!name||!Number.isFinite(price)||price<0)return;Services.addOrUpdate({id,name,price,icon:"✦"});e.currentTarget.reset();$("#service-id").value="";$("#cancel-service-edit").hidden=true;renderServices()});$("#cancel-service-edit").addEventListener("click",()=>{$("#service-form").reset();$("#service-id").value="";$("#cancel-service-edit").hidden=true});
function renderSettings(){const s=Storage.getSettings();$("#open-time").value=s.open;$("#close-time").value=s.close;$("#lunch-start").value=s.lunchStart||"";$("#lunch-end").value=s.lunchEnd||"";$("#special-dates").value=s.specialDates.join("\n");const days=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];$("#weekday-checks").innerHTML=days.map((d,i)=>`<label><input type="checkbox" value="${i}" ${s.weekdays.includes(i)?"checked":""}>${d}</label>`).join("")}
$("#settings-form").addEventListener("submit",e=>{e.preventDefault();const open=$("#open-time").value,close=$("#close-time").value,ls=$("#lunch-start").value,le=$("#lunch-end").value;if(open>=close){alert("O fechamento deve ser posterior à abertura.");return}const weekdays=[...$("#weekday-checks").querySelectorAll("input:checked")].map(x=>Number(x.value));if(!weekdays.length){alert("Selecione ao menos um dia de atendimento.");return}Storage.saveSettings({open,close,lunchStart:ls,lunchEnd:le,weekdays,specialDates:$("#special-dates").value.split(/\n/).map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x))});alert("Configurações salvas.");renderAdminCalendar()});
$("#reset-demo").addEventListener("click",()=>{if(confirm("Restaurar os dados iniciais? Todos os registros e ajustes locais serão substituídos.")){Storage.reset();renderAll()}});
function renderAll(){renderStats();renderAppointments();renderAdminCalendar();renderBlocks();renderServices();renderSettings()}
$("#year").textContent=new Date().getFullYear();
