import {CONFIG,money,dateISO,prettyDate,escapeHTML} from "./config.js";
import {Storage} from "./storage.js";
import {renderCalendar,slotAvailable,availableSlots,isDayBlocked} from "./calendar.js";
const $=s=>document.querySelector(s);let services=Storage.getServices(),selectedService=null,selectedDate=null,selectedTime=null,monthDate=new Date();monthDate.setDate(1);let formData=null;
const params=new URLSearchParams(location.search),requested=params.get("service");
function renderServices(){const wrap=$("#booking-services");wrap.innerHTML=services.map(s=>`<button type="button" class="booking-service ${selectedService?.id===s.id?"selected":""}" data-id="${escapeHTML(s.id)}"><strong>${escapeHTML(s.name)}</strong><span>${money(s.price)}</span></button>`).join("");wrap.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{selectedService=services.find(s=>s.id===b.dataset.id);selectedTime=null;renderServices();renderTimes();updateSummary()}));if(!selectedService&&services.length){selectedService=services.find(s=>s.id===requested)||services[0];renderServices()}}
function drawCalendar(){renderCalendar({monthDate,container:$("#calendar-days"),label:$("#month-label"),selected:selectedDate,onSelect:date=>{selectedDate=date;selectedTime=null;drawCalendar();renderTimes();updateSummary()}});const now=new Date();$("#prev-month").disabled=monthDate.getFullYear()===now.getFullYear()&&monthDate.getMonth()===now.getMonth()}
function renderTimes(){const wrap=$("#time-slots");wrap.innerHTML="";if(!selectedDate){$("#time-hint").textContent="Primeiro, selecione uma data.";wrap.innerHTML='<p class="empty-note">Os horários serão exibidos após escolher a data.</p>';return}$("#time-hint").textContent=prettyDate(selectedDate);const slots=availableSlots(selectedDate);if(!slots.length){wrap.innerHTML='<p class="empty-note">Não há horários configurados para esta data.</p>';return}slots.forEach(time=>{const available=slotAvailable(selectedDate,time),btn=document.createElement("button");btn.type="button";btn.className="time-slot"+(selectedTime===time?" selected":"");btn.disabled=!available;btn.innerHTML=available?time:`${time}<small>Reservado</small>`;btn.addEventListener("click",()=>{selectedTime=time;renderTimes();updateSummary()});wrap.append(btn)})}
function updateSummary(){const name=selectedService?.name||"Não selecionado",date=selectedDate?prettyDate(selectedDate):"—",time=selectedTime||"—",price=selectedService?money(selectedService.price):money(0);$("#aside-service").textContent=name;$("#aside-date").textContent=date;$("#aside-time").textContent=time;$("#aside-price").textContent=price;$("#summary-mini").textContent=selectedService&&selectedDate&&selectedTime?`${name} • ${date} • ${time} • ${price}`:"Selecione serviço, data e horário para conferir seu resumo."}
$("#prev-month").addEventListener("click",()=>{monthDate.setMonth(monthDate.getMonth()-1);drawCalendar()});$("#next-month").addEventListener("click",()=>{monthDate.setMonth(monthDate.getMonth()+1);drawCalendar()});
$("#client-form").addEventListener("submit",e=>{e.preventDefault();$("#form-error").textContent="";if(!selectedService||!selectedDate||!selectedTime){$("#form-error").textContent="Selecione um serviço, uma data e um horário disponível.";return}if(!slotAvailable(selectedDate,selectedTime)){selectedTime=null;renderTimes();updateSummary();$("#form-error").textContent="Este horário acabou de ficar indisponível. Escolha outro.";return}const fd=new FormData(e.currentTarget),name=String(fd.get("name")).trim(),phone=String(fd.get("phone")).replace(/\D/g,"");if(name.length<3||phone.length<10||phone.length>13){$("#form-error").textContent="Informe nome completo e telefone válido com DDD.";return}formData={name,phone,service:selectedService,date:selectedDate,time:selectedTime};$("#confirm-details").innerHTML=`<span>Cliente</span><strong>${escapeHTML(name)}</strong><span>Telefone</span><strong>${escapeHTML(phone)}</strong><span>Serviço</span><strong>${escapeHTML(selectedService.name)}</strong><span>Data</span><strong>${escapeHTML(prettyDate(selectedDate))}</strong><span>Horário</span><strong>${selectedTime}</strong><span>Valor</span><strong>${money(selectedService.price)}</strong>`;$("#confirm-modal").hidden=false});
$("#close-modal").addEventListener("click",()=>$("#confirm-modal").hidden=true);$("#back-edit").addEventListener("click",()=>$("#confirm-modal").hidden=true);
$("#confirm-booking").addEventListener("click",()=>{if(!formData)return;if(!slotAvailable(formData.date,formData.time)){$("#confirm-modal").hidden=true;$("#form-error").textContent="Este horário não está mais disponível. Selecione outro.";selectedTime=null;renderTimes();updateSummary();return}const record={id:"LC-"+Date.now().toString(36).toUpperCase(),name:formData.name,phone:formData.phone,serviceId:formData.service.id,serviceName:formData.service.name,price:formData.service.price,date:formData.date,time:formData.time,status:"Pendente",createdAt:new Date().toISOString()};const records=Storage.getAppointments();records.push(record);if(!Storage.saveAppointments(records)){$("#form-error").textContent="Não foi possível salvar neste navegador. Verifique o armazenamento.";return}$("#confirm-modal").hidden=true;$("#success-details").innerHTML=`<span>Código</span><strong>${record.id}</strong><span>Cliente</span><strong>${escapeHTML(record.name)}</strong><span>Serviço</span><strong>${escapeHTML(record.serviceName)}</strong><span>Data</span><strong>${escapeHTML(prettyDate(record.date))}</strong><span>Horário</span><strong>${record.time}</strong><span>Valor</span><strong>${money(record.price)}</strong>`;const msg=`Olá! Fiz uma simulação de agendamento na Barbearia Lecortes.%0ACliente: ${encodeURIComponent(record.name)}%0AServiço: ${encodeURIComponent(record.serviceName)}%0AData: ${encodeURIComponent(prettyDate(record.date))}%0AHorário: ${encodeURIComponent(record.time)}%0ACódigo: ${encodeURIComponent(record.id)}%0A%0AGostaria de confirmar o atendimento.`;$("#whatsapp-link").href=`https://wa.me/${CONFIG.whatsapp}?text=${msg}`;$("#success-modal").hidden=false;selectedTime=null;drawCalendar();renderTimes();updateSummary()});
document.querySelector(".menu-toggle")?.addEventListener("click",()=>{const nav=document.querySelector(".main-nav"),btn=document.querySelector(".menu-toggle"),open=nav.classList.toggle("open");btn.setAttribute("aria-expanded",String(open));btn.textContent=open?"×":"☰"});
$("#year").textContent=new Date().getFullYear();renderServices();drawCalendar();renderTimes();updateSummary();
